# Generated by Django 2.2.3 on 2019-07-10 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=128, verbose_name='采购人')),
                ('department', models.CharField(max_length=128, verbose_name='部门/职位')),
            ],
            options={
                'verbose_name': '采购人',
                'verbose_name_plural': '采购人',
            },
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=128, verbose_name='使用人')),
                ('consignee_company', models.CharField(max_length=128, verbose_name='公司名称')),
            ],
            options={
                'verbose_name': '使用人',
                'verbose_name_plural': '使用人',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128, verbose_name='品名')),
                ('pattern', models.CharField(max_length=64, verbose_name='型号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('stocks', models.IntegerField(default=0, verbose_name='库存数量')),
            ],
            options={
                'verbose_name': '配件表',
                'verbose_name_plural': '配件表',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=128, verbose_name='使用地点')),
                ('comment', models.CharField(blank=True, max_length=612, null=True, verbose_name='地点备注')),
            ],
            options={
                'verbose_name': '使用地点',
                'verbose_name_plural': '使用地点',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_title', models.CharField(max_length=128, verbose_name='使用目的')),
                ('comment', models.CharField(blank=True, max_length=612, null=True, verbose_name='目的备注')),
            ],
            options={
                'verbose_name': '使用目的',
                'verbose_name_plural': '使用目的',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=128, verbose_name='供货商')),
            ],
            options={
                'verbose_name': '供货商',
                'verbose_name_plural': '供货商',
            },
        ),
        migrations.CreateModel(
            name='Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateTimeField(verbose_name='出库时间')),
                ('comment', models.CharField(blank=True, max_length=612, null=True, verbose_name='出库备注')),
                ('quantities', models.IntegerField(verbose_name='出库数量')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Consignee', verbose_name='使用人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outs', to='inventory.Item', verbose_name='型号')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Position', verbose_name='使用地点')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Purpose', verbose_name='使用目的')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '出库',
                'verbose_name_plural': '出库',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Vendor', verbose_name='供货商'),
        ),
        migrations.CreateModel(
            name='In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateTimeField(verbose_name='入库时间')),
                ('comment', models.CharField(blank=True, max_length=612, null=True, verbose_name='入库备注')),
                ('quantities', models.IntegerField(verbose_name='数量')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Buyer', verbose_name='采购人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins', to='inventory.Item', verbose_name='货号')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '入库',
                'verbose_name_plural': '入库',
            },
        ),
    ]
