# Generated by Django 2.2.3 on 2019-07-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190710_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='in',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Purpose', verbose_name='目的'),
        ),
    ]
