# Generated by Django 2.2.3 on 2019-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_in_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='in',
            options={'verbose_name': '2.入库', 'verbose_name_plural': '2.入库'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '1.配件表', 'verbose_name_plural': '1.配件表'},
        ),
        migrations.AlterModelOptions(
            name='out',
            options={'verbose_name': '3.出库', 'verbose_name_plural': '3.出库'},
        ),
        migrations.AddField(
            model_name='item',
            name='is_screen',
            field=models.BooleanField(default=False, verbose_name='是否显示屏'),
        ),
        migrations.AddField(
            model_name='item',
            name='show_item',
            field=models.BooleanField(default=False, verbose_name='展示该项'),
        ),
    ]
